Include time.h
My PlatformIO IDE will give a compiler error if this inclusion is missing:

```
.piolibdeps/IotaClient/src/IotaWallet.cpp:200:35: error: 'time' was not declared in this scope
```